### ISSUE TITLE
pb_new_release fails when no releases exist

### ISSUE THREAD

**Issue by raymondben** [ropensci/piggyback#40]
Calling `pb_new_release` on a repo with no releases gives me:
```
Error in releases[[1]] : subscript out of bounds
```
I think it's because `piggyback:::pb_info()` returns `NULL` when no releases exist, but https://github.com/ropensci/piggyback/blob/master/R/pb_new_release.R#L38 is trying to subset that.

**Comment by cboettig** [comment]
Thanks for tracking that down!  Yup, looks like the return object from `gh` / the API must have changed and the comment there is no longer accurate

https://github.com/ropensci/piggyback/blob/02b261e1c92730d2fde5bb9eb74c45e5294fec58/R/pb_new_release.R#L36-L38

Interested in sending a quick PR for that?  Otherwise no worries I should be able to fix that one soon.

**Comment by roxannebeauclair** [comment]
I am also having this issue. I get the following error: 
```
Error in value[[3L]](cond) : 
  Cannot access release data for repository roxannebeauclair/..... Check that you have set a GITHUB_TOKEN and that at least one release on your GitHub repository page.
```
I should note that I have set a GITHUB_TOKEN in the .Renviron file. It displays when I type `Sys.getenv("GITHUB_TOKEN")`.

**Comment by cboettig** [comment]
@roxannebeauclair can you try installing the development version, restart R, and try again?

```r
remotes::install_github("ropensci/piggyback")
```

**Comment by roxannebeauclair** [comment]
@cboettig Unfortunately, that didn't work either. When I re-installed, I chose to install updates. I also re-issued a new token, that selected all of the options under "Repo" and "gist". Are there other options I should have selected when generating a token?

When I try use pb_new_release() and don't specify the repo (because i'm actually working within an R project), then I get this error message rather:

`Error in releases[[1]] : subscript out of bounds`

Specifying the precise repo, I still get the error from my previous post.

Do you think it could have something to do with the fact that I am not the original "owner" of the repo? Just a contributer?

**Comment by mskyttner** [comment]
Thanks for piggyback, it is great!

I ran into this issue too, and worked around it by manually creating an initial release at GitHub.

The error message I got when running `piggyback::pb_new_release(repo = "KTH-Library/cordis-data", tag = "v0.1.0")` (using piggyback from the master branch):

```r
#  Unprocessable Entity (WebDAV; RFC 4918) (HTTP 422).
```

It might be unrelated but there was also this notification that was sent from GitHub by email:

```bash
Your personal access token (Cordis PAT - uploading datasets to GitHub Releases) using libcurl/7.58.0 r-curl/4.3 httr/1.4.2 was used as part of a query parameter to access an endpoint through the GitHub API:

https://api.github.com/repositories/{identifier_here}/releases

Please use the Authorization HTTP header instead, as using the `access_token` query parameter is deprecated. If this token is being used by an app you don't have control over, be aware that it may stop working as a result of this deprecation.
```
