### ISSUE TITLE
Files downloaded with wrong names

### ISSUE THREAD

**Issue by Skourtis** [ropensci/piggyback#45]
Hi,

I really like the package and it's increadibly easy to use to get things on and off Git. 

Yesterday I've realised that the files I have on my local machine (Windows) do not contain the correct content, but manually checking the files in the release of my git repo, the files are correct there. It seems that when I use piggyback::pb_download the contents of the files are stored with wrong names (and in the wrong subfolders since I have files which belong in different subfolders in my R project). 

The files were uploaded from linux and it seems to be at least partially random because when I piggyback::pb_download twice in a row, the same file name has different content each time. For some reason I suspect this might be Windows related but here are the files I'm referring to. https://github.com/Skourtis/Translation/releases/tag/v1.0

Thank you,
Savvas

**Comment by cboettig** [comment]
definitely sounds frustrating!  I gather this might be a tricky one to reproduce, but can you see if you can make a reproducible minimal example, or at least provide more details? e.g. 
- can you reproduce this without subfolders?  
- without using two different machines?  
- What happens if you add the files 'manually' to a release, using the browser interface in GitHub, and then download them, or 
- upload via piggyback and then check manually what is on the release?

I haven't seen something like this before.  Remember that every step piggyback does can also be done via the GitHub browser though, so that could help pinpoint what part of the workflow files are correct and at what step they are suddenly getting crossed (e.g. if it is on download, upload, or something else).  

HTH!
