### ISSUE TITLE
pb_push not working?

### ISSUE THREAD

**Issue by mpadge** [ropensci/piggyback#5]
The following code should reproduce apparent inability of `pb_push` to actually push data
```
> library (piggyback)
> pb_new_release ("mpadge/junk", "v1")
> x <- runif (1e6)
> saveRDS (x, file = "data/x.Rds")
> pb_track (c ("data/*.Rds"))
> pb_push (repo = "mpadge/junk", tag = "v1")
> pb_list (repo = "mpadge/junk", tag = "v1")
character(0)
```
... nothing there! In contrast, this works:
```
> pb_upload ("data/x.Rds", repo = "mpadge/junk", tag = "v1")
> pb_list (repo = "mpadge/junk", tag = "v1")
[1] "data/x.Rds"
```

**Comment by mpadge** [comment]
Also re-cloning repo gives the following:
```
library(piggyback)
pb_track ("data/*.Rds")
pb_pull(repo = "mpadge/junk", tag = "v1")
#> Already up to date
```
And nothing is downloaded. Again, the explicit function works:
```
pb_download("data/x.Rds", repo = "mpadge/junk", tag = "v1")
#> 
  |=================================================================| 100%
```

**Comment by cboettig** [comment]
Thanks, I think this was due to my parsing of the globs (apparently `fs::dir_ls(glob="data/*.Rds")` does not behave in the same way as `ls data*/Rds`. I believe I have since fixed this issue in 43992c73c125445233300cf24b4122cc1dd3dc06 (works with my testing, but may fail elsewhere). 

Note that I think it will still fail if your `pb_track` pattern includes globs in the filepath, i.e. `data/*/*.Rds`, but hopefully that's a rare case.  I'm following up with Jim about that over in https://github.com/r-lib/fs/issues/118


Yeah, since `pb_upload` and `pb_download` don't have to guess what files you want they are a bit more robust.

**Comment by mpadge** [comment]
Hah, right you are, and I see you beat me to it by a mere 20 hours. Nice work! Just a thought for you to ponder, but it'd be useful for `pb_up/download` to do `md5` comparisons like `push/pull`. I'm guessing that'll come out in the review process anyway, so happy to close this issue for now. Thanks!

**Comment by cboettig** [comment]
Ha; sorry about that, I try to dog-food my stuff and stumbled across that bug yesterday; though I know it can be annoying to review something that is a moving target!  Hopefully I don't mess with many more things, but that seemed to be a pretty big hole. 


Yeah, good thought about the `md5` stuff.  

  Right, `pb_push` and `pb_pull` are essentially just thin wrappers around `pb_upload` & `pb_download` that add support for the `md5` comparisons by also uploading a `manifest.json` to store the hashes, (since sadly we can't just ask GitHub for the hashes of file assets).  Currently the logic for that is tied up in the logic for tracking, but like you say it should be possible to separate them.  

a related issue I'm pondering is that the md5 comparison only tells us whether or not the files are identical, not which one is "newer".  (technically we could inspect timestamps on the upload vs the filesystem but I have deep if possibly unjustified mistrust of timestamps).  So any thoughts on if/how to crack that nut in your review would also be most welcome!

**Comment by mpadge** [comment]
Hope you're not thinking that I'm doing the review, which I'm not. I'm just using. Anyway, I did see your documented comments about not being able to tell which is newer. but also didn't really see the need for this because:

1. If hashes are being compared on a push, then you'd have to presume the push is authorised and official, so let it be; and
2. If it's a pull, then comparing hashes will suffice anyway, so let it be.

If you really wanted to do it, and really wanted to avoid timestamps, then the only way that springs to mind would be to expand your `manifest` to include the entire sequence of hashes in temporal order. That'd be pretty easy (potential loss of backward compatibility notwithstanding).

**Comment by cboettig** [comment]
Cool, makes sense.  yeah, I thought about tracking all the hashes, but sounds too tricky (i.e. would basically need to reinvent git and handle the equivalent of 'merge conflicts' to deal with branching changes), but I think like you say that's all overkill.   Right, got confused, I think @annakrystalli is still seeking the second reviewer?
