### ISSUE TITLE
Warn when downloading/pulling older versions of files

### ISSUE THREAD

**Issue by mpadge** [ropensci/piggyback#8]
With respectful acknowledgment of your mistrust of timestamps, one place where these would actually be useful would be in order to implement a warning when downloading/pulling older versions of files, and consequently overwriting newer versions that may have since been created locally. That would be a really useful safety mechanism (for my current workflow at least). We're throwing files between lots of different people doing different tasks, and inadvertent overwrites do happen, and are potentially painful.

**Comment by cboettig** [comment]
Yeah, overwrites are definitely and issue so that's a good idea.  

Maybe we should go one further and simply provide the option of `use_timestamps` = `FALSE`/`warn`,/`TRUE` to `push`/`pull`.  `warn` would do as you say, `FALSE` is the current behavior, and `TRUE` would only push/pull those files with differing hashes AND older timestamps.  

Perhaps my mistrust of timestamps is not so warranted -- mostly arises from the fact that switching branches changes the timestamp, and from work on poorly maintained servers with drifting clocks long ago.  I guess since these files are not git managed, they would not be impacted by the latter.  A more empirically grounded opinion on timestamps might be called for.  (I agree that managing the hash tree a la git is the 'real' solution to version tracking, but I'm not going to implement that by hand).

**Comment by mpadge** [comment]
That sounds like a great solution. And yeah, the whole idea of `piggyback` is to avoid clogging up repos with the piggybacked files, so one can surely assume they very generally won't be part of a git tree, so should not have time stamps altered by any git operations. This would - for me - be a great boost!

**Comment by cboettig** [comment]
timestamp behavior now the default for upload / download
