### ISSUE TITLE
CRAN Submission

### ISSUE THREAD

**Issue by 1beb** [ropensci/piggyback#84]
Hey Carl! 

Do you have a plan for when you'll submit this to CRAN next? 

The package `wru` relies on this one, and #77 is happening across platforms and we don't want our users to have to set github personal access tokens. (It works as expected in current master). 

I'm happy to do the submission for you here if you don't have time. Let me know!

**Comment by cboettig** [comment]
@1beb thanks for the ping.

@tanho63 do you think we should release now or wait until we can merge #83?

**Comment by tanho63** [comment]
I think deleting releases is worth adding to the cran release and that feature is pretty much ready to me. 

Merging #83 is primarily held up because the newly rewritten tests don't have access to the right token, I think. If you can add a github pat to this repo's secrets under `CBOETTIG_TOKEN`, I think I can make it work with the `cboettig/piggyback-tests` repo this weekend and get the tests passing?

**Comment by tanho63** [comment]
Alternatively, could consider giving me GH permissions to add one of my tokens (or putting in a token I send to you by message) and I can have it work off of one of my test repos instead?

**Comment by tanho63** [comment]
@1beb v0.1.4 is now on CRAN as of July 19 (yesterday) - it may take a little bit for binaries to build. You could theoretically require this as minimum version, if desired. 

Closing as resolved 🎉

**Comment by 1beb** [comment]
Thank you Tan! Good work!
